services:
  app:
    build:
      context: .
      target: ${DOCKER_TARGET}
    container_name: pi5_musics-app
    depends_on:
      db:
        condition: service_healthy
      ms:
        condition: service_healthy
#      ml:
#        condition: service_started
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      MS_PASS: ${MS_PASS}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    volumes:
      - ./src:/var/www/html/src # transfert du code source
      - ./musics_storage:/var/www/music_data # persistance des musiques
    ports:
      - "${PORT_EXPOSE}:80"
    networks:
      - app-network

  db: # DataBase
    image: mariadb:12
    container_name: pi5_musics-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
      - pi5_musics-db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 3s
      retries: 10

  ms: # MeiliSearch
    image: getmeili/meilisearch:v1.40.0
    container_name: pi5_musics-ms
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MS_PASS}
      MEILI_ENV: ${DOCKER_TARGET}
    volumes:
      - pi5_musics-ms_data:/meili_data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7700/health" ]
      interval: 5s
      timeout: 3s
      retries: 10

#  ml: # MailHog
#    image: mailhog/mailhog:v1.0.1
#    container_name: pi5_musics-ml
#    ports:
#      - "1025:1025"
#      - "8025:8025"
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pi5_musics-db_data:
  pi5_musics-ms_data: