services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: ${DOCKER_TARGET}
    container_name: pi5_musics-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      ms:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      MS_PASS: ${MS_PASS}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    volumes:
      - ../src:/var/www/html/src # transfert du code source
      - pi5_musics-app_data:/var/www/music_data # persistance des musiques
    ports:
      - "${PORT_EXPOSE}:80"
    networks:
      - app-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nas.rule=Host(`unison.pi5.ovh`)"
      - "traefik.http.routers.nas.entrypoints=websecure"
      - "traefik.http.routers.nas.tls.certresolver=letsencrypt"
      - "traefik.http.services.nas.loadbalancer.server.port=80"

  db: # DataBase
    image: mariadb:12
    container_name: pi5_musics-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ../mysql_init:/docker-entrypoint-initdb.d
      - pi5_musics-db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 3s
      retries: 10

  ms: # MeiliSearch
    image: getmeili/meilisearch:v1.40.0
    container_name: pi5_musics-ms
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${MS_PASS}
      MEILI_ENV: ${DOCKER_TARGET}
    volumes:
      - pi5_musics-ms_data:/meili_data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7700/health" ]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  app-network:
    driver: bridge
  proxy-network:
    external: true

volumes:
  pi5_musics-app_data:
  pi5_musics-db_data:
  pi5_musics-ms_data:
