; --- VISIBILITÉ ---
expose_php = On

; --- GESTION DES ERREURS ---
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On

; --- SÉCURITÉ DES SESSIONS (Laxiste pour le dev local) ---
session.cookie_httponly = 1
session.cookie_secure = 0
session.cookie_samesite = "Lax"

; --- SOUPLESSE ---
opcache.enable = 0
memory_limit = 512M
max_execution_time = 600