; --- RESTRICTION DE L'ESPACE DE TRAVAIL ---
open_basedir = /var/www/html:/var/www/music_data:/var/www/maj:/tmp:/usr/bin

; --- DÉSACTIVATION DE FONCTIONS DANGEREUSES ---
disable_functions = passthru,popen,proc_open,show_source,highlight_file,sendmail,mail,parse_ini_file

; --- PROTECTION DES UPLOADS ---
file_uploads = On
max_file_uploads = 5
allow_url_fopen = Off
allow_url_include = Off

; --- DIVERS ---
max_input_time = 60